apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: openemr
  name: openemr
spec:
  replicas: 1
  selector:
    io.kompose.service: openemr
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/openemrocp-default: "true"
        io.kompose.service: openemr
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASS
              value: openemr
            - name: MYSQL_ROOT_PASS
              value: root
            - name: MYSQL_USER
              value: openemr
            - name: OE_PASS
              value: pass
            - name: OE_USER
              value: admin
          image: ' '
          name: openemr
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - mountPath: /var/log
              name: logvolume01
            - mountPath: /var/www/localhost/htdocs/openemr/sites
              name: sitevolume
      restartPolicy: Always
      volumes:
        - name: logvolume01
          persistentVolumeClaim:
            claimName: logvolume01
        - name: sitevolume
          persistentVolumeClaim:
            claimName: sitevolume
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - openemr
        from:
          kind: ImageStreamTag
          name: openemr:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
